# Cache file for storing TMDB ID to file path mappings
cache:
  path: /app/configs/cache.json

cache_expiration:
  emby: 3600     # Emby-fetch cache (seconds)
  match: 3600    # Matchresultat-cache (seconds)
  anilist: 3600  # AniList-cache (seconds)

# When Emberly should run automatically (cron-like)
schedule:
  hour: '3'
  minute: '0'

# Which data sources to use for trending media
sources:
  movies: true
  series: true
  anime: true
  tmdb: true
  trakt: true

# TMDb API settings
tmdb:
  api_key: ""

# Trakt API settings
trakt:
  client_id: ""
  client_secret: ""

# Trakt token – created automatically after first authentication
trakt_token:
  access_token: ""
  created_at: 0
  expires_in: 0
  refresh_token: ""
  scope: public
  token_type: bearer

# MyAnimeList API credentials and token cache
mal:
  client_id: ""
  client_secret: ""
  authorization:
    access_token: ""
    token_type: Bearer
    expires_in: 2678400
    refresh_token: ""
  localhost_url: ""
  cache_expiration: 60

# Define where Emberly should look for your actual media
media_paths:
  movies: /content/Movies
  series: /content/TV
  anime: /content/Anime

# Where symlinks to trending media should be created
symlink_paths:
  trending_movies: /media/movies
  trending_series: /media/tv
  current_season_anime: /media/anime

# Emby server settings
emby:
  instances:
    - api_key: ""
      url: http://localhost:8096
  #  - api_key: EMBY_API_KEY_2
  #    url: http://192.168.1.101:8096

# Limit on how many trending titles are processed per run
trending_limit:
  movies: 50
  series: 30
  anime: 40
